# your domain
domain: free886.herokuapp.com

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  - https://raw.githubusercontent.com/vipxkw/proxypool/master/config/source.yaml
